### ISSUE TITLE
2018 edition

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#24]
The minimum Rust version for this repo is presently 1.27.0.

I'd be interested in bumping that up to 1.31.0 and doing a 2018 edition upgrade on all crates.

**Comment by newpavlov** [comment]
We will need to start with trait crates first. Since it will involve bumping minor version we should update `generic-array` to v0.13 and use this chance to introduce other API changes if needed. I guess I will create a dedicated issue in traits repo.

Also I think we better to jump straight to 1.32. It has some import improvements over 1.31 and this way we will be in sync with `getrandom`/`rand`.

**Comment by newpavlov** [comment]
See RustCrypto/traits#43

**Comment by tarcieri** [comment]
All crates have been updated to the 2018 edition
